spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_agent_system # 配置你的数据库引擎
    username: root
    password: 1
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-f5e167a6d77c4078b2433db1859c352f
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-f5e167a6d77c4078b2433db1859c352f
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192